version: '3.7'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        container_name: web
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web/dist:/var/www/html